### PR TITLE
[#103] Update gems

### LINKED ISSUE #103: Update gems to prevent security vulnerabilities
Gems need to be updated to prevent security vulnerability errors that fail linter checks. This will probably need to be done regularly, so this issue will be reopened whenever it is needed.

### PR DESCRIPTION
**Pull request by walldmtd**
Closes #103. Regular update to fix security vulnerabilities in gems.

### CODE REVIEW

File: db/schema.rb [hunk 1]
```diff
@@ -42,6 +42,12 @@
     t.index ["user_id"], name: "index_sessions_on_user_id"
   end
 
+  create_table "test_items", charset: "utf8mb4", collation: "utf8mb4_0900_ai_ci", force: :cascade do |t|
+    t.string "name"
+    t.datetime "created_at", null: false
+    t.datetime "updated_at", null: false
+  end
+
```
Comment (Naleac) [inline db/schema.rb:50]: Should this schema update be in this PR?

Comment (walldmtd) [reply db/schema.rb:50]: Idk, not really sure where that came from. I'll remove it.

**Review by Naleac — APPROVED** [review]
